name: drupalcommerce
recipe: drupal9
config:
  webroot: web

services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database.drupal9.internal
  drupalcommerce:
    type: mariadb
    portforward: true
    creds:
      user: drupalcommerce
      password: drupalcommerce
      database: drupalcommerce
